### ISSUE TITLE
Subscription is not available

### ISSUE THREAD

**Issue by youstable** [razorpay/razorpay-whmcs#11]
As RazorPay is now supporting recurring payments in India we wanted to integrate the same with our website [https://youstable.com](url) which is using WHMCS and already has this module installed but unfortunately there is no option to apply subscription.

Kindly enable this feature for WHMCS users.

**Comment by mayankamencherla** [comment]
Working on this locally. Will create PR by tomorrow EOD cc @ccrims0n

**Comment by yashodhank** [comment]
It will be very useful add on, thanks. looking forward to test.

**Comment by youstable** [comment]
Is there any update on this ?

**Comment by pulkit8** [comment]
Hi, 

Can anyone confirm if this feature is not yet implemented in the repo? I was planning to get razorpay gateway for my website www.basezap.com and I was told that subscription is available (Yes, I mentioned whmcs).

**Comment by pmjcreations** [comment]
Hey @pulkit8,

Either you talked to a Sales Rep, or they didn't read/listen to the word WHMCS correctly.

This module won't support Subscriptions, yet.

**Comment by pulkit8** [comment]
> Hey @pulkit8,
> 
> Either you talked to a Sales Rep, or they didn't read/listen to the word WHMCS correctly.
> 
> This module won't support Subscriptions, yet.

Yes, Sales Rep. I guess razorpay needs to provide better training to Sales rep. They claimed many things which turned out to be false. Wasted much of their and our time.

**Comment by pmjcreations** [comment]
It is a shame that Razorpay isn't responding here at all, for two years now.

Have they abandoned this module?

@captn3m0 @ccrims0n

**Comment by youstable** [comment]
They are just ignoring this module its been 3 years requesting this update and on email they informed our team that module will be released mid 20

**Comment by pmjcreations** [comment]
Mid of 2020?

**Comment by youstable** [comment]
Yeah but don't think they will do it in 2020 as well ..

**Comment by youstable** [comment]
WHMCS Module still not updated they fukin dont care about us.
ᐧ

**Comment by pmjcreations** [comment]
I stopped using Razorpay with my WHMCS.

For a less than 1% of my customers who can't use my current payment gateway, I use Razorpay.

**Comment by youstable** [comment]
I am also removing RazorPay will make Stripe for default payment
ᐧ

**Comment by pmjcreations** [comment]
That sounds like a plan, @youstable. 

Meanwhile, some human or bots marked your previous comment as disruptive.

Anyways, it is not productive for me to participate here with Razorpay team or ask for status in their Chat section.

They might be ignoring us and just focussing on their neo-banking dream.

Just like they don't care me, I too don't bother for them.

**Comment by youstable** [comment]
No! We already integrated STRIPE in our WHMCS that seems working fine with
Domestic payments we are doing some documentations for Internation payments
then we will remove RazorPay as they are 2nd gateway allowing us
International Transactions after PayPal.
ᐧ

**Comment by harman28** [comment]
I'm sorry you've had to wait this long for a response. This plugin is admittedly in desperate need of an update. We haven't been able to get around to it for a while now, but do intend on updating it within the next 2 months. 

Note that this update will only cover regular payments, and will not include Subscriptions. There is currently no plan to add support for Subscription support for WHMCS. I've shared your interest with the relevant team though, so they can take it into account for future planning.

In the meantime, I'd suggest checking out our [hosted Subscriptions product](https://razorpay.com/docs/subscriptions/dashboard/), which allows you to control subscriptions from your Razorpay dashboard, to see if it might serve your use case.

**Comment by harman28** [comment]
Closing this as there is no plan to support Subscriptions at the moment. See [Hosted Subscrptions](https://razorpay.com/docs/subscriptions/dashboard/) for a possibly viable alternative.
