### ISSUE TITLE
Can't Get Through the Payment

### ISSUE THREAD

**Issue by xaif** [razorpay/razorpay-whmcs#19]
Whenever I am doing a transaction I am getting this URL and I am getting blank page http://account.webverge.io//modules/gateways/callback/razorpay.php

**Comment by ramth05** [comment]
> Whenever I am doing a transaction I am getting this URL and I am getting blank page http://account.webverge.io//modules/gateways/callback/razorpay.php

@xaif , can you please check why you are redirected to `http` from `https`

**Comment by xaif** [comment]
I have checked it and everything is working fine now. I had to call the support once.
