### ISSUE TITLE
Support for WHMCS 7

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-whmcs#6]
Need to add support for WHMCS 7

**Comment by captn3m0** [comment]
Notifications: 75829

**Comment by albingeorge** [comment]
Our plugin is already compatible with WHMCS 7. Tested it locally by setting up a WHMCS 7 instance and installing our plugin within.

PR for updating the README:
https://github.com/razorpay/razorpay-whmcs/pull/8#pullrequestreview-63975043
